# Generated by Django 4.2 on 2023-06-05 05:40

from django.db import migrations, models
from chat.models import Shop, User
import django.db.models.deletion
import random
import chat


def create_models(apps, schema_editor):
    # Userデータを追加
    User.objects.create(name="hikaru")
    User.objects.create(name="taro")
    User.objects.create(name="hanako")
    name = ['game', 'book', 'pc', 'phone', 'water', 'salt', 'watch', 'iron', 'paper', 'ticket',
            'head', 'eye', 'hand', 'leg', 'english', 'japanese']
    money = [100, 200, 300, 400, 500]
    size = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    quantity = [1, 2, 3, 4, 5, 6, 7, 8, 9, 100]
    color = ['red', 'blue', 'green', 'white', 'black', 'yellow', 'pink', 'orange']
    date = ['2023-05-30', '2023-05-26', '2023-05-23', '2023-05-20', '2023-05-15', '2023-05-11',
            '2023-05-01']
    time = ['09:00', '09:30', '10:00', '12:22', '13:59', '23:00', ]
    sold = ["はい", "いいえ"]
    manager = ["hikaru", "taro", "hanako"]
    for i in range(0, 100):
        Shop.objects.create(
            name=random.choice(name), money=random.choice(money),
            size=random.choice(size), quantity=random.choice(quantity),
            color=random.choice(color), date=random.choice(date),
            time=random.choice(time),
            sold=random.choice(sold), manager_id=random.choice(manager)
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(default='no named', max_length=100, unique=True,
                                          verbose_name='担当者')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='商品名')),
                ('money', models.IntegerField(null=True, verbose_name='金額')),
                ('size', models.IntegerField(null=True, verbose_name='大きさ')),
                ('quantity', models.IntegerField(null=True, verbose_name='個数')),
                ('color', models.CharField(default='', max_length=10, verbose_name='色')),
                ('date', models.DateField(null=True, verbose_name='日付')),
                ('time', models.TimeField(null=True, verbose_name='時間')),
                ('sold', models.CharField(default='', max_length=10, verbose_name='売り切れ')),
                ('note', models.CharField(default='', max_length=10, verbose_name='備考')),
                ('manager_check',
                 models.BooleanField(default=False, verbose_name='担当者チェック')),
                ('manager', chat.models.ForeignKeyWithStrToField(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    to='chat.user', to_field='name', verbose_name='担当者'
                )),
            ],
        ),
        migrations.RunPython(create_models, lambda apps, schema_editor: None)
    ]
